'use strict';

require('./Rules/nonewcommand.js');
require('./Rules/noautonumformulas.js');
require('./Rules/noautonumbiblio.js');
require('./Rules/notoest.js');
require('./Rules/no_nontrivial-comments.js');
require('./Rules/no_trivial-comments.js');
require('./Rules/separate$$.js');
require('./Rules/separate$.js');
require('./Rules/splitrows80.js');
require('./Rules/no_env_equation.js');
require('./Rules/no_env_equation*.js');
require('./Rules/dot_ending.js');
require('./Rules/space_after_comma.js');
require('./Rules/forbid_upsilon.js');
require('./Rules/forbid_vspace.js');
require('./Rules/comma_before_gde.js');
require('./Rules/sin_must_be_command.js');
require('./Rules/tg_must_be_command.js');
require('./Rules/Bibitem_exist.js');
require('./Rules/no-mathit-in-formula.js');
require('./Rules/no-foreignlanguage.js');
require('./Rules/force_geqslant.js');
require('./Rules/force_leqslant.js');
require('./Rules/Russian_quotes.js');
