'use strict';

var rulesets = {
	vzmsh2017: {
		title: 'ВЗМШ-2017',
		url: 'https://vzmsh.math-vsu.ru/rules/',
		rules: [
			['nonewcommand', 1],
			['noautonumformulas', 1],
			['noautonumbiblio', 1],
		],
		comment: 'Отсутствие ошибок является необходимым условием подачи тезисов. Достаточное условие проверяется вручную!',
	},
	mz: {
		title: 'Математические заметки',
		url: 'http://www.mathnet.ru/php/authornotes.phtml?jrnid=mzm&option_lang=rus&wshow=authornotes',
		rules: [
			['Bibitem_exist', 1],
			['udk_exist', 1],
			['udk_onlyone', 1],
			['noinlinefrac', 0.5],
			['no_frac_in_sub_sup', 0.5],
			['noinlinesumprod', 0.5],
		],
		comment: '',
		examples: [
			{
				title: 'С библиографией',
				source: 'mz-01',
			},
			{
				title: 'Без библиографии',
				source: 'mz-02-no-biblio',
			},
		],
	},
	smzh: {
		title: 'Сибматжурнал',
		url: 'http://a-server.math.nsc.ru/publishing/smz/for_authors.php',
		rules: [
			['separate$$', 1],
			['separate$', 1],
			['splitrows80', 1],
			['sin_must_be_command', 1],
			['no_nontrivial-comments', 1],
			['no_trivial-comments', 1],
			['nonewcommand', 1],
			['noautonumformulas', 1],
			['noautonumbiblio', 1],
			['notoest', 1],
			['no_env_equation', 1],
			['no_env_equation*', 1],
		],
		comment: '',
		examples: [
			{
				title: 'Простой пример',
				source: 'smzh-1',
			},
		],
	},
	rtf2latex: {
		title: 'После конвертера rtf2latex',
		url: 'https://github.com/nickkolok/rtf2latex2e',
		rules: [
			['longmapsto_instead_of_delta', 1],
			['manual_paragraph_format', 1],
			['empty_text_options', 1],
			['forbid_vspace', 1],
			['rtf2latex_subunicode_artifacts', 1],
			['no_spaces_at_line_ending', 1],
			['space_after_comma', 1],
			['no_space_before_comma', 1],
			['no_newline_before_comma', 1],
			['sin_must_be_command', 1],
			['tg_must_be_command', 1],
			['forbid_upsilon', 1],
			['comma_before_gde', 1],
		],
		comment: '',
	},
	openMeschersky: {
		title: 'Проект OpenMeschersky',
		url: 'https://github.com/nickkolok/OpenMeschersky',
		rules: [
			['splitrows80', 1],
			['manual_paragraph_format', 1],
			['empty_text_options', 1],
			['eof_newline', 1],
			['eof_newline_only_one', 1],
			['no_spaces_at_line_beginning', 1],
			['no_spaces_at_line_ending', 1],
			['dot_ending', 1],
			['eyo', 1],
			['space_after_comma', 1],
			['no_space_before_comma', 1],
			['numbers_must_be_in_formula', 1],
			['sin_must_be_command', 1],
			['tg_must_be_command', 1],
			['forbid_upsilon', 1],
			['comma_before_gde', 1],
		],
		comment: '',
	},
	vzms2018: {
		title: 'ВЗМШ-2018',
		url: 'https://github.com/nickkolok/vzms2018',
		rules: [
			['manual_paragraph_format', 1],
			['empty_text_options', 1],
			['separate_latin_and_cyrillic', 1],
			['eyo', 1],
			['space_after_comma', 1],
			['no_space_before_comma', 1],
			['sin_must_be_command', 1],
			['tg_must_be_command', 1],
			['forbid_upsilon', 1],
			['comma_before_gde', 1],
			['no-mathit-in-formula', 1],
			['force_tagged_norm', 1],
			['force_geqslant', 1],
			['force_leqslant', 1],
			['Russian_quotes', 1],
			['force_babel_quoted_emdash', 1],
			['force_emdash_after_formula_cyr', 1],
			['force_emdash_in_text_cyr', 1],
			['force_babel_quoted_hyphen', 1],
		],
		comment: '',
		examples: [
			{
				title: 'Простой пример',
				source: 'smzh-1',
			},
		],
	},
	vvmsh2018: {
		title: 'ВВМШ-2018',
		url: '', //TODO
		rules: [
			['manual_paragraph_format', 1],
			['empty_text_options', 1],
			//['eyo', 1],
			['space_after_comma', 1],
			['no_space_before_comma', 1],
			['no_newline_before_comma', 1],
			['sin_must_be_command', 1],
			['tg_must_be_command', 1],
			['forbid_upsilon', 1],
			//['comma_before_gde', 1],
			['no-mathit-in-formula', 1],
			//['force_geqslant', 1],
			//['force_leqslant', 1],
			['Russian_quotes', 1],
			['forbid_English_quotes', 1],
		],
		comment: '',
	},
	wxmaximaTransit: {
		title: 'После wxMaxima',
		url: '', //TODO
		rules: [
			['no-mathit-in-formula', 1],
			['no-mathrm-in-formula', 1],
			['maxima_forbid_cdot', 1],
			['maxima_underscore', 1],
		],
		comment: '',
	},
	ITOGI: {
		title: 'ITOGI',
		url: '', //TODO
		rules: [
			['Russian_quotes', 1],
			['forbid_English_quotes', 1],
			['manual_paragraph_format', 1],
			['empty_text_options', 1],
			['eyo', 1],
			['space_after_comma', 1],
			['no_space_before_comma', 1],
			['no_newline_before_comma', 1],
			['sin_must_be_command', 1],
			['tg_must_be_command', 1],
			['forbid_upsilon', 1],
			['comma_before_gde', 1],
			['no_env_eqnarray', 1],
			['no_env_eqnarray*', 1],
			['force_$$_to_equation*', 1],
			['noinlinesumprod', 0.5],
			['force_babel_quoted_emdash', 1],
			['collapse_cite', 1],
		],
		comment: '',
	},
};

rulesets.defaultSet = rulesets.vzmsh2017;
module.exports = rulesets;
